RobotId: 1

# rrt params
N_SAMPLE: 1000
robot_size: 0.2
avoid_dist: 0.15
steer_dist: 0.3
allow_path_theta: 1.57   # pi / 3 * 2

# dwa params
w_max: 0.4
wa: 2.0
w_reso: 0.05
safe_dist: 0.25
penalty: 6.0
dt: 0.2  # 0.1
predict_time: 3.0
delay_predict_time: 8.0
goal_cost_gain: 5.0
dist_cost_gain: 0.5
global_path_cost_gain: 10.0